name: 'Integration'

on:
  pull_request: 
    branches: [ production, development ]
  push:
    branches: [ production, development ]

jobs:
  setup:
    name: Setup node and environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Cache ts-node-dev and rush
        id: cacheTsNodeDev
        uses: actions/cache@v2
        env:
          cache-name: cache-modules
        with:
          path: |
            /usr/local/lib/node_modules/ts-node-dev
            /usr/local/lib/node_modules/@microsoft/rush
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}

      - name: Global dependencies
        if: steps.cacheTsNodeDev.outputs.cache-hit != 'true'
        run: npm install -g ts-node-dev @microsoft/rush

  audit:
    name: Audit for vulnerabilities
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
          
      - run: node common/scripts/install-run-rush.js audit

  lint:
    name: Lint code for standarlization
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
          
      - run: node common/scripts/install-run-rush.js lint

  analyze:
    name: Analyze code for vulnerabilities
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'javascript'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1


  build:
    name: Build all packages
    needs: [audit, lint, analyze]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        with:
          build: true

  test_1:
    name: Test general packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
          
      - run: node common/scripts/install-run-rush.js test

  test_2:
    name: Test database packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
          
      - run: echo 'implement database tests'

  publish:
    name: Publish release packages
    needs: [test_1, test_2]
    runs-on: ubuntu-latest
    if: ${{ github.event.release.body != '' && success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
          
      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE: ${{ github.event.release.body }}
        run: node common/scripts/install-run-rush.js bump
