name: 'Publish'

on:
  push:
    branches: [ development ]

jobs:
  setup:
    name: Setup node and environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

  publish:
    name: Verify version bump
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Cache builds
        id: cacheBuilds
        uses: actions/cache@v2
        env:
          cache-name: cache-builds
        with:
          path: ./packages/**/dist
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}
          
      - name: Publish changes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          COMMIT: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node common/scripts/install-run-rush.js publish:new